name: Deployment Generator
on:
  push:
    branches:
      - main
  
jobs:
  create-deployment:
    name: Create Deployment
    runs-on: ubuntu-20.04
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    # - name: Install npm dependencies
    #   run: npm install

    - name: Configure PHP 8.0.28
      uses: shivammathur/setup-php@master
      with:
        php-version: 8.1
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, zip
    - name: Install composer dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Generate deployment
      run: tar -czf ${{ github.sha }}.tar.gz --exclude .git --exclude .github --exclude .gitignore --exclude .vscode --exclude composer.json --exclude composer.lock --exclude README.md --exclude .gitattributes --exclude .gitignore --exclude package.json --exclude package-lock.json --exclude dbh.php *

    - name: Upload deployment
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: ${{ github.sha }}.tar.gz
      
  release-on-server:
    name: Release on server
    needs: create-deployment
    runs-on: ubuntu-20.04
    env:
      DEPLOY_DIRECTORY: /home/${{ secrets.USERNAME }}/${{ secrets.DEPLOY_DIRECTORY }}
    steps:
    - name: Download deployment
      uses: actions/download-artifact@v3
      with:
        name: app-build
    - name: Upload deployment
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: ${{ github.sha }}.tar.gz
        target: ${{ env.DEPLOY_DIRECTORY }}/
    - name: Unzip deployment and remove zip
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          tar -xzf ${{ env.DEPLOY_DIRECTORY }}/${{ github.sha }}.tar.gz -C ${{ env.DEPLOY_DIRECTORY }}
          rm ${{ env.DEPLOY_DIRECTORY }}/${{ github.sha }}.tar.gz